import { createApp } from "vue";
import App from "./App.vue";
import { installZoomGuards } from "./lib/zoomGuards";
import "driver.js/dist/driver.css";
import "./features/onboarding/tour.css";
import "./styles/fonts.css";
import "./styles/tokens.css";
import "./styles/base.css";
import "./styles/layout.css";
import "./styles/components/sidebar/index.css";
import "./styles/components/topbar.css";
import "./styles/components/editor.css";
import "./styles/components/corner-pocket.css";
import "./styles/components/dialog.css";
import "./styles/components/code-ai-optimize.css";
import "./styles/components/design-card.css";
import "./styles/components/dialog-enter.css";
import "./styles/components/dialog-exit.css";
import "./styles/components/notebook/index.css";
import "./styles/components/runtime-loading.css";
import "./styles/components/screening-dialog.css";

installZoomGuards();
createApp(App).mount("#app");
