// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddScriptNoteImages(arg1, arg2) {
  return window['go']['bridge']['App']['AddScriptNoteImages'](arg1, arg2);
}

export function BootstrapWorkspace() {
  return window['go']['bridge']['App']['BootstrapWorkspace']();
}

export function CheckForUpdates(arg1) {
  return window['go']['bridge']['App']['CheckForUpdates'](arg1);
}

export function CreateCodeAIVersion(arg1) {
  return window['go']['bridge']['App']['CreateCodeAIVersion'](arg1);
}

export function CreateScript(arg1) {
  return window['go']['bridge']['App']['CreateScript'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['bridge']['App']['CreateWorkspace'](arg1);
}

export function DeleteCodeAIVersion(arg1, arg2) {
  return window['go']['bridge']['App']['DeleteCodeAIVersion'](arg1, arg2);
}

export function DeleteDesignCard(arg1, arg2) {
  return window['go']['bridge']['App']['DeleteDesignCard'](arg1, arg2);
}

export function DeleteScript(arg1) {
  return window['go']['bridge']['App']['DeleteScript'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['bridge']['App']['DeleteWorkspace'](arg1);
}

export function DownloadUpdate() {
  return window['go']['bridge']['App']['DownloadUpdate']();
}

export function ExportScenePackage(arg1) {
  return window['go']['bridge']['App']['ExportScenePackage'](arg1);
}

export function ExportWorkspacePackage(arg1) {
  return window['go']['bridge']['App']['ExportWorkspacePackage'](arg1);
}

export function GenerateDesignCardFromSelection(arg1) {
  return window['go']['bridge']['App']['GenerateDesignCardFromSelection'](arg1);
}

export function GetAISettings() {
  return window['go']['bridge']['App']['GetAISettings']();
}

export function GetDesignCard(arg1, arg2) {
  return window['go']['bridge']['App']['GetDesignCard'](arg1, arg2);
}

export function GetEnvironmentStatus() {
  return window['go']['bridge']['App']['GetEnvironmentStatus']();
}

export function GetOnboardingState() {
  return window['go']['bridge']['App']['GetOnboardingState']();
}

export function GetScreeningState() {
  return window['go']['bridge']['App']['GetScreeningState']();
}

export function GetScriptContent(arg1) {
  return window['go']['bridge']['App']['GetScriptContent'](arg1);
}

export function GetScriptList() {
  return window['go']['bridge']['App']['GetScriptList']();
}

export function GetScriptNote(arg1) {
  return window['go']['bridge']['App']['GetScriptNote'](arg1);
}

export function GetSubscriptionStatus(arg1) {
  return window['go']['bridge']['App']['GetSubscriptionStatus'](arg1);
}

export function GetUpdateStatus() {
  return window['go']['bridge']['App']['GetUpdateStatus']();
}

export function ImportScenePackage() {
  return window['go']['bridge']['App']['ImportScenePackage']();
}

export function ImportScenePackageFromPath(arg1) {
  return window['go']['bridge']['App']['ImportScenePackageFromPath'](arg1);
}

export function ImportWorkspacePackage() {
  return window['go']['bridge']['App']['ImportWorkspacePackage']();
}

export function InitializeApp() {
  return window['go']['bridge']['App']['InitializeApp']();
}

export function InstallUpdateAndRestart() {
  return window['go']['bridge']['App']['InstallUpdateAndRestart']();
}

export function ListCodeAIVersions(arg1) {
  return window['go']['bridge']['App']['ListCodeAIVersions'](arg1);
}

export function ListDesignCardVersions(arg1, arg2) {
  return window['go']['bridge']['App']['ListDesignCardVersions'](arg1, arg2);
}

export function ListDesignCards(arg1) {
  return window['go']['bridge']['App']['ListDesignCards'](arg1);
}

export function NextScreeningPage() {
  return window['go']['bridge']['App']['NextScreeningPage']();
}

export function OpenSubscriptionPurchase() {
  return window['go']['bridge']['App']['OpenSubscriptionPurchase']();
}

export function OptimizeDesignCard(arg1) {
  return window['go']['bridge']['App']['OptimizeDesignCard'](arg1);
}

export function PreviousScreeningPage() {
  return window['go']['bridge']['App']['PreviousScreeningPage']();
}

export function RebuildRuntime() {
  return window['go']['bridge']['App']['RebuildRuntime']();
}

export function RefreshWorkspace(arg1) {
  return window['go']['bridge']['App']['RefreshWorkspace'](arg1);
}

export function RemoveScriptNoteImage(arg1, arg2) {
  return window['go']['bridge']['App']['RemoveScriptNoteImage'](arg1, arg2);
}

export function RenameScript(arg1, arg2) {
  return window['go']['bridge']['App']['RenameScript'](arg1, arg2);
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['bridge']['App']['RenameWorkspace'](arg1, arg2);
}

export function ReorderScripts(arg1, arg2) {
  return window['go']['bridge']['App']['ReorderScripts'](arg1, arg2);
}

export function ResolveOnboardingState(arg1, arg2) {
  return window['go']['bridge']['App']['ResolveOnboardingState'](arg1, arg2);
}

export function SaveAISettings(arg1) {
  return window['go']['bridge']['App']['SaveAISettings'](arg1);
}

export function SaveAndRun(arg1, arg2) {
  return window['go']['bridge']['App']['SaveAndRun'](arg1, arg2);
}

export function SaveScript(arg1, arg2) {
  return window['go']['bridge']['App']['SaveScript'](arg1, arg2);
}

export function SaveScriptNote(arg1, arg2) {
  return window['go']['bridge']['App']['SaveScriptNote'](arg1, arg2);
}

export function StartAIWorkflow(arg1) {
  return window['go']['bridge']['App']['StartAIWorkflow'](arg1);
}

export function StartDesignCardSession(arg1) {
  return window['go']['bridge']['App']['StartDesignCardSession'](arg1);
}

export function StartScreening(arg1) {
  return window['go']['bridge']['App']['StartScreening'](arg1);
}

export function StopAIWorkflow(arg1) {
  return window['go']['bridge']['App']['StopAIWorkflow'](arg1);
}

export function StopCurrentRun() {
  return window['go']['bridge']['App']['StopCurrentRun']();
}

export function StopDesignCardSession(arg1) {
  return window['go']['bridge']['App']['StopDesignCardSession'](arg1);
}

export function StopScreening() {
  return window['go']['bridge']['App']['StopScreening']();
}

export function SwitchWorkspace(arg1) {
  return window['go']['bridge']['App']['SwitchWorkspace'](arg1);
}

export function ToggleScreeningDraw() {
  return window['go']['bridge']['App']['ToggleScreeningDraw']();
}

export function ToggleScreeningLiveZoom() {
  return window['go']['bridge']['App']['ToggleScreeningLiveZoom']();
}

export function UpdateDesignCardPlan(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['UpdateDesignCardPlan'](arg1, arg2, arg3);
}

export function UpdateOnboardingState(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['UpdateOnboardingState'](arg1, arg2, arg3);
}
